server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096

    producer:
      acks: all
      retries: 3
      linger-ms: 20
      batch-size: 16384

    consumer:
      group-id: notification-group
      json-trusted-packages: ru.itk.kafka.notification.dto

    topics:
      sent_orders:
        name: sent_orders

      user_notification:
        name: user_notification
        replicas: 3
        partitions: 3

      user_notification-dlq:
        name: user_notification-dlq
        replicas: 2
        partitions: 3


async:
  kafka-executor:
    core-pool-size: 4
    max-pool-size: 8
    queue-capacity: 100

retries:
  retry-policy: 3
  back-off-period: 1000